Template xml
exactpro/epfast pull request #43
Opened 2020-03-16 11:40 UTC by KsovreliAna

2020-03-23 15:44 UTC, ASitnikov requested changes

2020-03-23 15:44 UTC, ASitnikov commented on build.gradle.kts
> +    runtimeOnly("com.sun.xml.bind:jaxb-impl:2.4.0-b180830.0438")
change it back to 2.3.2

2020-03-23 15:44 UTC, ASitnikov commented on build.gradle.kts
> +    testImplementation("org.assertj:assertj-core:3.6.2")
move it up, where other testImplementations reside

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/TemplateNsXmlParent.java
> +public interface TemplateNsXmlParent {
Rename to `NamespaceProvider`. It should have 2 methods: one for application ns, another for template ns. Make sure the method names in these methods don't have same names as methods for xml fields in classes that implement this interface. If it's the case either rename methods in interface or methods in classes. I think the later is simpler as we can easily add `xml` prefix to method name.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +        protected String namespace;
It won't be needed, see comment in `ApplicationIdentity`. Same as corresponding getter/setter defined in this class

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +    public abstract static class IdentityBase implements Identity {
rename to `AbstractIdentity`

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +public class AfterUnmarshal {
Remove. Place enclosed classes in different files.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +        public String parentNs;
Change to `private final NamespaceProvider nsProvider`. Place it in parent class. Its value can be passed in constructor.
The way you've done it wont work in all cases. The namespace may be defined not in parent, but in grandparent. So it's better to delegate walking this chain to our xml classes.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/FieldInstrContent.java
> +public class FieldInstrContent extends FieldOpXml implements FieldInstruction {
This class should implement 'ApplicationNsProvider' interface. See other comments.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/FieldInstrContent.java
> +
Add `private NamespaceProvider parentNsProvider`. Set it in `afterUnmarshal()`

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/IdentityXml.java
> +public class IdentityXml implements Identity {
This class should be removed. All its usages should be replace with `ApplicationIdentity`.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/InitialValueXml.java
> +public class InitialValueXml implements FieldOperator {
Rename to `FieldOperatorXml`.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/FieldOpXml.java
> +public class FieldOpXml {
rename to FiledBaseXml

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/OpContextXml.java
> +public class OpContextXml extends InitialValueXml {
Rename to `DictionaryFieldOperatorXml`.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/ReferenceImpl.java
> +public class ReferenceImpl implements Reference {
I think references should be able to get namespace from parent elements as well. Please check.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/TemplateXml.java
> +    private String ns;
Rename `applicactionNs` or `applicationNamespace`. Please check that names in all classes are consistent and have either "application" or "template" in their names.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/TemplateXml.java
> +    public void setNs(String ns) {
Names for xml parsing should keep naming closer to xml names. So this name is OK.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/Charset.java
> +public enum Charset {
Add `Xml` suffix for consistency.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/InstructionAdapter.java
> +public class InstructionAdapter extends XmlAdapter<InstructionXml, Instruction> {
Rename to `InstructionAdapter`.

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/instructionfields/StringFieldXml.java
> +        if (charset == Charset.ASCII) {
Better use switch with throwing exception in default (if charset is neither ASCII or UNICODE)

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/instructionfields/integerfields/Int32Xml.java
> +    public Instruction toInstruction() {
Can it be placed in `FieldInstrContent`?

2020-03-23 15:44 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/instructionfields/integerfields/Int32Xml.java
> +public class Int32Xml extends FieldInstrContent implements Int32Field, InstructionXml {
Add "field" to all field class names, i.e. `Int32FieldXml`

2020-03-26 07:56 UTC, KsovreliAna commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +        protected String namespace;
Why? What do you mean?

2020-03-26 08:05 UTC, KsovreliAna commented on src/main/java/com/exactpro/epfast/template/xml/FieldInstrContent.java
> +public class FieldInstrContent extends FieldOpXml implements FieldInstruction {
But I thought providers are only Templates, Template, Group and Sequence

2020-03-26 08:20 UTC, KsovreliAna commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +        public String parentNs;
What should I do with NsXmlParent class?

2020-03-27 08:26 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/FieldInstrContent.java
> +public class FieldInstrContent extends FieldOpXml implements FieldInstruction {
Yes, but you can't access templates directly from mantissa copy operator. It's easier to make all classes in chain from operator to templates providers than to add logic which tries to find nearest ancestor with defined namespace

2020-03-27 08:26 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +        protected String namespace;
It will be requested from namespace provider.

2020-03-27 08:26 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/helper/AfterUnmarshal.java
> +        public String parentNs;
Replace it with `NamespaceProvider`

2020-04-03 08:19 UTC, ASitnikov requested changes
I think you don't really understand how this thing with namespace providers should work. So I'm inclined to accept this change and let you start writing unit tests.

Before that remove test which prints template as JSON and rename `FieldBaseXml` to `AbstractFieldXml` .

2020-04-03 08:19 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/ApplicationIdentity.java
> +        return "";
It should be the constant I've mentioned in our group chat

2020-04-03 08:19 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/ByteVectorFieldXml.java
> +    private ApplicationIdentity lengthFieldId = new ApplicationIdentity(null);
You should always pass something to constructor. And I guess this something will be `this` in 100% of cases.

2020-04-03 08:19 UTC, ASitnikov commented on src/main/java/com/exactpro/epfast/template/xml/TemplatesXml.java
> +        return XML_NAMESPACE;
It should be `Reference.DEFAULT_NAMESPACE` or something alike. I don't remember how it's named exactly. Ask Vakho if you can't find it.

2020-04-06 09:26 UTC, ASitnikov approved these changes
Looks good enough. Lets move to the tests

2020-04-06 09:33 UTC, merged